generate-spec
Fix #11 
```
$ ~/Repositories/openapi-extractor/generate-spec 
Info: app: Extracting OpenAPI spec for spreed 18.0.0-dev.6
PHP Fatal error:  Uncaught Exception: Error: Response definitions: Type alias 'SpreedRoomShare' has to start with 'Talk'
in /home/nickv/Nextcloud/Repositories/openapi-extractor/src/Logger.php:33
Stack trace:
#0 /home/nickv/Nextcloud/Repositories/openapi-extractor/generate-spec(139): OpenAPIExtractor\Logger::error()
#1 {main}
thrown in /home/nickv/Nextcloud/Repositories/openapi-extractor/src/Logger.php on line 33
```
Since namespace is optional, I added a check and fallback for the current behaviour. After removing the namespace line in Talk it "worked again" using "Spreed":
```
$ ~/Repositories/openapi-extractor/generate-spec 
Info: app: Extracting OpenAPI spec for …
```
=> fix: Support namespace when defined in info.xml

src/OpenApiType.php
Fixes https://github.com/nextcloud/openapi-extractor/issues/36
Merging the enums is necessary because otherwise every sub type of the union type will be it's own enum with only one possible value.
=> fix: Do not convert union types to string

generate-spec, src/Route.php
Closes https://github.com/nextcloud/openapi-extractor/issues/34
=> feat: Use path parameter defaults from routes

src/Logger.php, src/LoggerException.php
Since https://github.com/nextcloud/openapi-extractor/commit/80cfa10060e41060413d18820d0359cae5a9c056 the exceptions that were thrown didn't show the full message (including level and context) anymore.
=> fix(logger): Show full message when throwing LoggerException

src/OpenApiType.php
Closes https://github.com/nextcloud/openapi-extractor/issues/12
`mixed` is illegal because it will absorb every other type and lead to invalid specifications. No changes required in any of the apps that currently support openapi-extractor.
=> feat: Prevent mixed in unions and intersections

generate-spec
`$classMethod` is only available in the for loop and is stored in `$methodFunction` for later use.
=> fix: Do not access variable outside of for loop

generate-spec
It's not necessary to use a reference here (and psalm can't handle it properly).
=> refactor: Remove usage of reference

generate-spec, src/Helpers.php, src/OpenApiType.php
Inline the one function and move the other to Helpers where it belongs.
=> refactor: Cleanup left over helper functions

generate-spec, merge-specs, src/ControllerMethod.php, src/Helpers.php
Better readability and more performant.
=> refactor: Cleanup array handling

src/OpenApiType.php
For query parameters we have to convert booleans into integers as they are only accepted that way. This sets the `enum` field on the returned integer schema to indicate that these are the only possible values.
Can be tested in the server.
=> feat: Make boolean quirk an enum

generate-spec
The previous check was a bit complicated and could break in case the of extended Controller classes with different names. Relying on the key in the routes should always be save.
=> refactor: Simplify OCS check

generate-spec
Reduces the time needed for running on server with spreed, notifications and tables from 7.3s to 4.8s.
I know I could only parse the controllers that are in the routes once and not every available controller, but this needs to be done anyway for the upcoming routing changes.
=> perf: Only parse controllers once

merge-specs
https://github.com/nextcloud/openapi-extractor/pull/57 introduced this and with it all map values were converted to string automatically which is wrong.
=> fix(merge-specs): Remove accidental value casting

generate-spec, src/Helpers.php
At one point I thought it would be a good idea to rename `index` to `list` because it is more intuitive, but it can have unintended side effects, so we should stop doing that.
=> fix: Stop renaming parts of the operationId

.github/workflows/test-repositories.yml
Extracted from https://github.com/nextcloud/openapi-extractor/pull/24 to avoid the self-canceling CI workflows.
=> fix(CI): Don't cancel "in Repositories" from the normal testing job

generate-spec
Now that we don't print a lot of messages anymore it's good to show a message when done so it's clear that there was no problem.
=> feat(generate-spec): Add a little done message when the spec is generated

src/Helpers.php
Broken after https://github.com/nextcloud/openapi-extractor/pull/24.
The problem is that allOf, oneOf and anyOf contain lists of schemas, while properties contains a map of schemas and additionalProperties is a schema directly. Using recursive walk solves this and will not encounter problems in the future.
The dashboard app is affected (https://github.com/nextcloud/server/pull/42888/files#diff-34caa6070d1d05fddc37174348f4f3a601f7d9a3c01816e68c1303b449cd575b)
=> fix(Helpers): Fix ref collection

src/Route.php
Happens in https://github.com/nextcloud/server/blob/master/apps/user_ldap/appinfo/routes.php, but in this particular case all the newly discovered routes have to be ignored.
=> fix(routing): Extract routes even with multiple registerRoutes calls

src/ControllerMethodParameter.php, src/Helpers.php, src/UnsupportedExprException.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Extracted from https://github.com/nextcloud/openapi-extractor/pull/73 and added tests.
When a parameter had an array as default value it wasn't parsed correctly.
The output of the spec still says the type is string, but that has to do with https://github.com/nextcloud/openapi-extractor/issues/88#issuecomment-1908557979 and can't be fixed that easily here.
=> fix(helpers): Fix parsing arrays

generate-spec, src/Route.php, tests/lib/Controller/RoutingController.php, tests/openapi-administration.json, tests/openapi-full.json
Server PR is following soon, but the added test can already verify the behaviour.
=> feat(routing): Support new Route attribute

generate-spec
Will fix the CI failure in https://github.com/nextcloud/server/actions/runs/7987586055/job/21810358990?pr=42801 which is caused by the controllers being read in a different order on my machine vs. the CI.
I already had this problem once with the capabilities files, so this was easy to figure out...
=> fix: Load controllers in a deterministic order

src/Helpers.php
Closes https://github.com/nextcloud/openapi-extractor/issues/99
Tags should be limited to certain characters to avoid developers using strange things that could break generators.
=> feat(scopes): Limit tag names

README.md
Thanks a lot @blizzz, I would have written a template soon if you hadn't done it already :)
=> docs: Link to template repo for the CI workflow

generate-spec
The check should have been after the new attribute routes are loaded and not before.
=> fix(routes): Correctly show warning about missing routes

generate-spec, src/Helpers.php, src/OpenApiType.php
The previous code was not really readable and probably didn't perform well.
=> refactor: Stop using array_merge to create associative arrays

generate-spec
https://github.com/nextcloud/openapi-extractor/pull/104 accidentally changed the order of the properties for path parameters. To avoid unnecessary diffs that would appear when using the new version I'm reverting it to the old order (which is also a bit more readable).
=> fix: Keep old path parameter property order

src/ControllerMethod.php, src/Helpers.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-full.json, tests/openapi.json
=> Add correct response for OCS*Exceptions

src/ResponseType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/108
=> fix(ResponseType): Correctly add empty responses for 204/304

src/ResponseType.php
Forgot to adjust the message in https://github.com/nextcloud/openapi-extractor/pull/111.
Basically the same as https://github.com/nextcloud/server/pull/44726.
=> fix(ResponseType): Fix error message about 204 not allowing custom headers

.github/workflows/test-repositories.yml
Some apps might not have a spec with a default scope. The .noopenapi file was introduced to explicitly state that an app doesn't support OpenAPI and every other app is expected to support it.
=> fix(ci): Test against all server apps

generate-spec, src/Route.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/98
Tags are not longer used for the operationId because it is possible to tag two controller methods with the same names in two different controllers with the same tag and the output would be the same operationId. Talk is currently affected by this problem.
The failure results in a panic and can not be skipped because the result would be an invalid spec.
The CI for Talk will fail because it currently has a controller method with two routes that are not unique.
=> fix: Ensure operationIds are unique

generate-spec, src/ControllerMethod.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Closes https://github.com/nextcloud/openapi-extractor/issues/25
=> feat(ControllerMethod): Warn about required password confirmation

.github/workflows/test-repositories.yml
Closes https://github.com/nextcloud/openapi-extractor/issues/86
=> feat(ci): Add more apps to test against

src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
The current assumption that a union type is equivalent to oneOf is not correct.
The PHP type annotation
```php
array{a: string}|array{a: string, b: int}
```
would mean the JSON would always be either
```json
{"a": ""}
```
or
```json
{"a": "", "b": 0}
```
The OpenAPI spec mandates that exactly ONE schema matches the data. No more no less.
Our generated spec would look like
```json
{
"oneOf": [
{
"type": "object"
"properties": {
"a": {
"type": "string"
}
}
},
{
"type": "object"
"properties": {
"a": {
"type": "string"
}
"b": {
"type": "integer"
}
}
}
]
}
```
The first schema would always match both possibilities (additional properties are always allowed and ignored), so the assumption that only one schema ever matches is not true.
We don't want to use anyOf all the time though, because it …
=> fix(OpenApiType): Use anyOf instead of oneOf for conflicting types

generate-spec
Closes https://github.com/nextcloud/openapi-extractor/issues/3
Quite a big performance improvement:
server: 11s -> 3s
spreed: 4s -> 2s
=> perf: Limit files searched for capabilities

src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/123
=> fix(OpenApiType): All floats are doubles

src/ControllerMethod.php, src/Helpers.php, src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/124
=> fix(OpenApiType): Use maxItems instead of maxLength for arrays

merge-specs
When using a glob to include the other specs and the core spec is also among them the capabilities would get included twice.
https://github.com/nextcloud/neon/issues/2004
=> fix(merge-specs): Avoid duplicate capabilities entries

generate-spec, src/OpenApiType.php, tests/openapi-administration.json, tests/openapi-full.json
Closes https://github.com/nextcloud/openapi-extractor/issues/88
This fixes a lot of cases where the query parameters was just typed as string because it was not possible to correctly set the type.
=> fix: Move all parameters from query to JSON body

src/OpenApiType.php
JSON objects can only be indexed by string, so any other type has to be prevented.
In theory we could parse `array<int, ...>` as simple JSON array, but that is very likely not the intended use since there is no way to skip int keys in JSON and thus `array<...>` or `list<...>` should be used.
For reference: https://github.com/nextcloud/tables/pull/1169
=> fix(OpenApiType): Prevent arrays indexed by non-strings

src/ControllerMethod.php, src/ControllerMethodParameter.php
Enables better error messages by telling the user where exactly the problem occurred.
=> fix: Provider better context for failures

generate-spec, src/ControllerMethod.php, src/OpenApiType.php, src/ResponseType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/144
The undefined serialization behavior warning can probably be fixed by implementing the deepObject serialization style (as described in https://swagger.io/docs/specification/serialization), but it needs a lot more investigation and refactoring that is out of scope for this partial revert to fix the current mess.
=> Fix request body usage for GET/HEAD/DELETE requests

src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/147
Classic case of PHP array handling again... If the array value is empty it is always converted to `[]` in JSON while it should be `{}` in case the type is something like `array<string, string>`.
=> fix(OpenApiType): Use correct default values for empty object types

generate-spec, merge-specs, src/Logger.php
While this flag was meant to speed up development, people are starting to abuse it any ignore any errors.
They won't even know that the spec isn't complete due to all the errors.
=> fix: Remove dangerous --continue-on-error flag

CHANGELOG.md, composer.json
As far as I understand the `version` field can be left empty since we are going to use git tags to denote the version: https://getcomposer.org/doc/04-schema.md#version
=> chore(release): v1.0.0

CHANGELOG.md, src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/140
=> fix(OpenApiType): Clean whitespace in description fields

generate-spec, src/OpenApiType.php, tests/lib/Controller/AdminSettingsController.php, tests/lib/Controller/ExAppSettingsController.php, tests/lib/Controller/FederationController.php, tests/lib/Controller/RoutingController.php, tests/lib/Controller/SettingsController.php, tests/lib/ResponseDefinitions.php
Fixes https://github.com/nextcloud/openapi-extractor/issues/33
=> fix(OpenApiType): Forbid using ambigous array syntaxes

generate-spec, src/Route.php, tests/lib/Controller/RoutingController.php, tests/openapi-administration.json, tests/openapi-full.json
Closes https://github.com/nextcloud/openapi-extractor/issues/179
Due to https://github.com/nextcloud/server/pull/46760 index.php routes can now also use the OCS-APIRequest header to pass the CSRF protections.
=> feat: Include CSRF protected index.php routes

generate-spec, tests/openapi-administration.json, tests/openapi-full.json
The route key controls the path and the extended class controls the response.
Any sane API would not mix these, but Groupfolders does so anyway :melting_face:
The assumption that these are always the same is not given, thus we need to properly handle it...
We actually already had some test endpoints that triggered this case, but until now generated the wrong documentation (without the OCS wrap).
=> fix(OCS): Fix route vs Controller differences

src/OpenApiType.php
Closes https://github.com/nextcloud/openapi-extractor/issues/177
=> feat(OpenApiType): Warn about non-required nullable properties

generate-spec.php, tests/lib/Controller/PlainController.php, tests/openapi-full.json, tests/openapi.json
index.php routes are not meant to be used for stable APIs.
Unfortunately we have a lot of legacy APIs that still use them so we can't just ignore them entirely.
This changes the default behavior to ignore them, but one can still manually include them by changing the scope for a method or controller.
=> feat(generate-spec): Ignore index.php routes by default

generate-spec.php, src/ControllerMethod.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
For https://github.com/nextcloud/openapi-extractor/issues/151
=> feat(ControllerMethod): Add documentation for CORS endpoints

src/ResponseType.php
Additional response type added by PR https://github.com/nextcloud/server/pull/49995
=> enh: add stream generator response

generate-spec.php, src/OpenApiType.php, tests/lib/ResponseDefinitions.php, tests/openapi-full.json, tests/openapi.json
Closes https://github.com/nextcloud/openapi-extractor/issues/10.
I also tried comments at the end of the line, but those are completely ignored and do not appear in the parser output. I'm not sure if this is a phpdoc-parser bug or not, but having the option to set any comments at all is much better than having it not.
Also adding comments in front of a type alias doesn't work either, so it's not possible yet to set the description of an entire schema.
=> feat(OpenApiType): Support comments in object array types

generate-spec.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-federation.json, tests/openapi-full.json
Fixes https://github.com/nextcloud/openapi-extractor/issues/222
The array_merge was overwriting existing operations if they had the same path and belonged to different scopes.
Check the spreed changes to see the impact and that it fixes the originally reported issue.
=> fix(scopes): Correctly merge full scopes if multiple operations with the same path belong to different scopes

.github/workflows/test-repositories.yml, merge-specs.php
https://github.com/nextcloud/openapi-extractor/issues/225
Otherwise `{}` from JSON will turn into `[]` in PHP and then into `[]` in JSON which is not valid.
=> fix(merge-specs): Use objects instead of associative arrays to fix empty JSON objects

generate-spec.php, src/ControllerMethod.php
We already log an error if no response is returned from a controller method, but that is also satisfied if a `@throws` annotation is present.
Luckily with the return statements we can easily check if any is present (there might be controller methods that only throw or never return), so a separate error is now logged in case the code has a `return` statement but no `@return` annotation.
=> fix(ControllerMethod): Log an error if return statements are detected but no @return annotation is present

generate-spec.php, src/ControllerMethod.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
If the getHeader() call is not directly in the controller method we can't detect that, but better than parsing nothing at all.
https://github.com/nextcloud/openapi-extractor/issues/89
=> feat(ControllerMethod): Parse request headers

generate-spec.php, src/ControllerMethod.php, src/ControllerMethodParameter.php, src/OpenApiType.php, tests/appinfo/routes.php, tests/lib/Controller/SettingsController.php, tests/openapi-administration.json, tests/openapi-full.json
Closes https://github.com/nextcloud/openapi-extractor/issues/237
=>  feat(ControllerMethod): Support getParam()
